# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rag.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
#from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trag.proto\x12\x03rag\"\x07\n\x05\x45mpty\"]\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x02\x12\x0c\n\x04size\x18\x04 \x01(\x02\x12\r\n\x05image\x18\x05 \x01(\t\x12\x0c\n\x04shop\x18\x06 \x01(\t\"-\n\x0bProductList\x12\x1e\n\x08products\x18\x01 \x03(\x0b\x32\x0c.rag.Product2=\n\x0eProductService\x12+\n\x0bGetProducts\x12\n.rag.Empty\x1a\x10.rag.ProductListB\nZ\x08./rag_pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rag_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\010./rag_pb'
  _globals['_EMPTY']._serialized_start=18
  _globals['_EMPTY']._serialized_end=25
  _globals['_PRODUCT']._serialized_start=27
  _globals['_PRODUCT']._serialized_end=120
  _globals['_PRODUCTLIST']._serialized_start=122
  _globals['_PRODUCTLIST']._serialized_end=167
  _globals['_PRODUCTSERVICE']._serialized_start=169
  _globals['_PRODUCTSERVICE']._serialized_end=230
# @@protoc_insertion_point(module_scope)
